dist: trusty
language: python
python:
  - "3.6"
notifications:
  email:
    recipients:
      - nialldouglas14@gmail.com

env:
 - __="Build"
 - __="Test"
 - __="Install"

install: "pip install -r requirements.txt"

script:
 -
   if [ "$__" = "Build" ]; then
     python setup.py build;
   fi
 -
   if [ "$__" = "Test" ]; then
     python setup.py test;
   fi
 -
   if [ "$__" = "Install" ]; then
     python setup.py install;
     static-website-activitypub --version;
   fi
